### ISSUE TITLE
Kernel panic after bluetooth keyboard disconnect

### ISSUE THREAD

**Issue by JaviLib** [AsahiLinux/linux#352] opened 2024-12-21 15:38 UTC
Tested with 2 different keyboards, one of them a Logitech k380, the other one is a chinese RX909. Fedora 41 Asahi Remix. Keyboard and everything works great until I discconect a bluetooth keyboard. At that right moment, the system crashes and cannot work anymore. No new applicacions can be open, no service can be started again. I have to cut power and power on again to continue.

```
# cat /proc/version 
Linux version 6.12.4-400.asahi.fc41.aarch64+16k (mockbuild@dbd791be80ff4eb5ab11f922c9dde1fc) (gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3), GNU ld version 2.43.1-4.fc41) #1 SMP PREEMPT_DYNAMIC Thu Dec 12 10:57:58 UTC 2024
```

Mac mini m1.

Logs:

```
dic 21 16:14:53 fedora kernel: Unable to handle kernel paging request at virtual address ffff99e29650c008
dic 21 16:14:53 fedora kernel: Mem abort info:
dic 21 16:14:53 fedora kernel:   ESR = 0x0000000096000005
dic 21 16:14:53 fedora kernel:   EC = 0x25: DABT (current EL), IL = 32 bits
dic 21 16:14:53 fedora kernel:   SET = 0, FnV = 0
dic 21 16:14:53 fedora kernel:   EA = 0, S1PTW = 0
dic 21 16:14:53 fedora kernel:   FSC = 0x05: level 1 translation fault
dic 21 16:14:53 fedora kernel: Data abort info:
dic 21 16:14:53 fedora kernel:   ISV = 0, ISS = 0x00000005, ISS2 = 0x00000000
dic 21 16:14:53 fedora kernel:   CM = 0, WnR = 0, TnD = 0, TagAccess = 0
dic 21 16:14:53 fedora kernel:   GCS = 0, Overlay = 0, DirtyBit = 0, Xs = 0
dic 21 16:14:53 fedora kernel: swapper pgtable: 16k pages, 48-bit VAs, pgdp=00000009d53ac000
dic 21 16:14:53 fedora kernel: [ffff99e29650c008] pgd=10000009d705c003, p4d=10000009d705c003, pud=0000000000000000
dic 21 16:14:53 fedora kernel: Internal error: Oops: 0000000096000005 [#1] SMP
dic 21 16:14:53 fedora kernel: Modules linked in: dm_crypt uinput snd_seq_dummy snd_hrtimer rfcomm snd_seq snd_seq_device sunrpc nf_conntrack_netbios_ns nf_conntrack_broadcast nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib uhid nf>
dic 21 16:14:53 fedora kernel:  macsmc snd apple_admac udc_core nvmem_apple_efuses clk_apple_nco soundcore apple_sio spi_apple pinctrl_apple_gpio apple_wdt i2c_pasemi_platform spmi_apple_controller i2c_pasemi_core apple_dart xhci_>
dic 21 16:14:53 fedora kernel: CPU: 2 UID: 0 PID: 81 Comm: kworker/2:1 Tainted: G S                 6.12.4-400.asahi.fc41.aarch64+16k #1
dic 21 16:14:53 fedora kernel: Tainted: [S]=CPU_OUT_OF_SPEC
dic 21 16:14:53 fedora kernel: Hardware name: Apple Mac mini (M1, 2020) (DT)
dic 21 16:14:53 fedora kernel: Workqueue: events hidinput_led_worker
dic 21 16:14:53 fedora kernel: pstate: 81400009 (Nzcv daif +PAN -UAO -TCO +DIT -SSBS BTYPE=--)
dic 21 16:14:53 fedora kernel: pc : __srcu_read_lock+0x48/0x98
dic 21 16:14:53 fedora kernel: lr : dispatch_hid_bpf_output_report+0x70/0x118
dic 21 16:14:53 fedora kernel: sp : ffff800080b77ca0
dic 21 16:14:53 fedora kernel: x29: ffff800080b77ca0 x28: 0000000000000000 x27: 0000000000000000
dic 21 16:14:53 fedora kernel: x26: 0000000000000000 x25: 0000000000000000 x24: ffff3f11813b7605
dic 21 16:14:53 fedora kernel: x23: ffff3f1287185e38 x22: 0000000000000000 x21: ffff3f1287185e08
dic 21 16:14:53 fedora kernel: x20: ffff3f1287184000 x19: 0000000000000001 x18: 0000000000000000
dic 21 16:14:53 fedora kernel: x17: 2e323433423a4436 x16: 34303a353030302f x15: 646968752f637369
dic 21 16:14:53 fedora kernel: x14: 0000000000000000 x13: 0000000000000030 x12: 0101010101010101
dic 21 16:14:53 fedora kernel: x11: 7f7f7f7f7f7f7f7f x10: fefefefefefefeff x9 : ffffa530c7d8a7a8
dic 21 16:14:53 fedora kernel: x8 : ffff3f119b2c8e71 x7 : 0000000000001e08 x6 : 0000000000001e38
dic 21 16:14:53 fedora kernel: x5 : ffff3f118cee4b00 x4 : 0000000000000000 x3 : 0000000000000000
dic 21 16:14:53 fedora kernel: x2 : 0000000000000001 x1 : 0000000000000008 x0 : ffff99e29650c008
dic 21 16:14:53 fedora kernel: Call trace:
dic 21 16:14:53 fedora kernel:  __srcu_read_lock+0x48/0x98
dic 21 16:14:53 fedora kernel:  dispatch_hid_bpf_output_report+0x70/0x118
dic 21 16:14:53 fedora kernel:  hid_hw_output_report+0x60/0xd0
dic 21 16:14:53 fedora kernel:  hidinput_led_worker+0xb0/0x110
dic 21 16:14:53 fedora kernel:  process_one_work+0x180/0x430
dic 21 16:14:53 fedora kernel:  worker_thread+0x25c/0x380
dic 21 16:14:53 fedora kernel:  kthread+0xf4/0x110
dic 21 16:14:53 fedora kernel:  ret_from_fork+0x10/0x20
dic 21 16:14:53 fedora kernel: Code: d53cd040 8b020021 d2800022 8b000020 (f822001f) 
dic 21 16:14:53 fedora kernel: ---[ end trace 0000000000000000 ]---
dic 21 16:14:53 fedora kernel: note: kworker/2:1[81] exited with preempt_count 1
dic 21 16:14:55 fedora abrt-dump-journal-oops[921]: abrt-dump-journal-oops: Found oopses: 1
dic 21 16:14:55 fedora abrt-dump-journal-oops[921]: abrt-dump-journal-oops: Creating problem directories
dic 21 16:14:55 fedora abrt-server[4881]: Deleting problem directory oops-2024-12-21-16:14:55-921-0 (dup of oops-2024-12-19-01:44:26-1156-0)
dic 21 16:14:55 fedora abrt-applet[2376]: g_app_info_should_show: assertion 'G_IS_APP_INFO (appinfo)' failed
dic 21 16:14:55 fedora abrt-notification[4891]: [🡕] System encountered a non-fatal error in __srcu_read_lock()
dic 21 16:14:55 fedora gnome-shell[2046]: JS ERROR: Error: 429 is not a valid value for enumeration Status
                                          get_soup_v3/</<@file:///home/javi/.local/share/gnome-shell/extensions/crypto@alipirpiran.github/api/request.js:24:21
                                          @resource:///org/gnome/shell/ui/init.js:21:20
dic 21 16:14:56 fedora abrt-dump-journal-oops[921]: Reported 1 kernel oopses to Abrt
dic 21 16:15:34 fedora systemd[1879]: Created slice background.slice - User Background Tasks Slice.
dic 21 16:15:34 fedora systemd[1879]: Starting systemd-tmpfiles-clean.service - Cleanup of User's Temporary Files and Directories...
dic 21 16:15:34 fedora systemd[1879]: Finished systemd-tmpfiles-clean.service - Cleanup of User's Temporary Files and Directories.
dic 21 16:17:33 fedora systemd-logind[837]: Power key pressed short.
dic 21 16:17:33 fedora kernel: macsmc-rtkit 23e400000.smc: RTKit: syslog message: apComms.cpp:375: SMC HID Event: 01 01 01
dic 21 16:17:36 fedora kernel: macsmc-rtkit 23e400000.smc: RTKit: syslog message: apComms.cpp:375: SMC HID Event: 01 fe 01
dic 21 16:17:36 fedora kernel: macsmc-hid macsmc-hid: Power button held down
dic 21 16:17:37 fedora kernel: macsmc-rtkit 23e400000.smc: RTKit: syslog message: apComms.cpp:375: SMC HID Event: 01 00 01
dic 21 16:17:37 fedora kernel: macsmc-hid macsmc-hid: Triggering forced shutdown!

```

**Comment by marcan** [comment] 2024-12-21 19:01
Duplicate of #344 .

**Closed as completed by marcan** 2024-12-21 19:01 UTC
