### ISSUE TITLE
6.2-rc3-7 no keyboard/no graphics

### ISSUE THREAD

**Issue by ToCodeABluejay** [AsahiLinux/linux#114] opened 2023-02-28 18:54 UTC
Hello! I have built and installed the latest 6.2RC kernel. It boots perfectly fine, however, I experience two problems. Firstly, the graphics do not work, so I had to disable sddm in order to see a login screen. Secondly, when I arrived at said login screen, I had no keyboard input. And this was after building the kernel using `make mod2yesconfig` as well...

**Comment by ToCodeABluejay** [comment] 2023-02-28 22:38
Replicated with upstream `asahi-dirty` kernel 6.1.0, aka the latest upstream commit to this repository...

**Comment by SjonHortensius** [comment] 2023-03-01 08:43
this sounds like a duplicate of https://github.com/AsahiLinux/linux/issues/95

is someone already running the released 6.2 or 6.2.1 kernel?

**Comment by ToCodeABluejay** [comment] 2023-03-12 18:16
I do not know, but I will try one of the recent releases and comment back on how it went!

**Comment by ToCodeABluejay** [comment] 2023-03-14 19:49
Tried with 6.2.6 with no success

**Comment by ToCodeABluejay** [comment] 2023-03-14 19:51
Also, this is not a copy of #95 as the TTYs are not working...

**Comment by jannau** [comment] 2023-03-14 20:10
What do you mean by `6.2.6`? The Linux stable kernel `6.2.6` or the tag `asahi-6.2-6`? The former can not work since it misses drivers. This is not the right place to seek support for that.
If it is the latter (`asahi-6.2-6`) you need to provide much more details. This is very very likely a problem of your build/installation. Nobody has seem / reported keyboard issues with the packages build recent tags. There is no guarantee that random `asahi-*` tags work at all. Please do not build them blindly if you can't identify problems with them yourself.

You provide no information in this ticket which would allow to help you. I'm not even sure with which commits or on which device you see the problems.

**Comment by ToCodeABluejay** [comment] 2023-03-19 01:03
The device is the 2020 Macbook Air. It was asahi-6.2-6. I simply downloaded the tagged version and built using `make LLVM=1` and then I install, ran `mkinitcpio -P` after creating a preset for the kernel version, and updated grub. I have since deleted the installation as I am now currently using the disk space for another installation. I can re-install it and test it out again, and I could provide a `kern.log` after it for debug info as well. However, something tells me that your assumption is correct, and perhaps there is a step in the build process that is necessary to fix this which I am unaware of. It just would not make much sense otherwise...For instance, I was unaware of the PKGBUILDs provided. This would make perfect sense. I simply did not build using the right method...

**Comment by marcan** [comment] 2023-06-15 12:46
Selfbuilt kernels with random configs are not supported, nor is building random tags. There are specific configs required to make things work. You also need to provision device trees etc. If you're not using our packaged kernels, you're basically on your own.

**Closed as completed by marcan** 2023-06-15 12:46 UTC

**Comment by ToCodeABluejay** [comment] 2023-06-15 14:29
Everything worked fine once I used the PKGBUILD. I can customize the config without it going haywire as well. Zero issues. 👍
